# Applications for external files.
[applications]
excel = 'C:\Program Files (x86)\Microsoft Office\root\Office16\EXCEL.EXE'
pdf = 'C:\Program Files\Tracker Software\PDF Viewer\PDFXCview.exe'
python = 'C:\Program Files\Python310\python.exe'
vlc = 'C:\Program Files (x86)\VideoLAN\VLC\vlc.exe'
word = 'C:\Program Files (x86)\Microsoft Office\root\Office16\WINWORD.EXE'


# Settings for uploading Presenter images.
[server]
user = 'jerome'
host = 'www.rollenspiel-wiki.de'
#password = ''
port = 22
pscp = 'C:\Program Files\PuTTY\pscp.exe'
target = '/var/www/html/jerome/lorekeeper/lorekeeper.png'
