MONSTER_TABLE = (('Climate/Terrain', 'climate'),
                 ('Frequency', 'frequency'),
                 ('Organization', 'organization'),
                 ('Activity Cycle', 'activity'),
                 ('Diet', 'diet'),
                 ('Intelligence', 'intelligence'),
                 ('Treasure', 'treasure'),
                 ('Alignment', 'alignment'),
                 ('No. Appearing', 'appearing'),
                 ('Armor Class', 'armor_class'),
                 ('Movement', 'movement'),
                 ('Hit Dice', 'hit_dice'),
                 ('THAC0', 'thac0'),
                 ('No. of Attacks', 'attacks'),
                 ('Damage/Attack', 'damage'),
                 ('Special Attacks', 'offensive'),
                 ('Special Defenses', 'defensive'),
                 ('Magic Resistance', 'magic_resistance'),
                 ('Size', 'size'),
                 ('Morale', 'morale'),
                 ('XP Value', 'xp'))
