DEFAULT_ABILITIES = """
name;type;actions;text
All-Around Vision;general;;[Name] can see in all directions simultaneously, and therefore can\'t be flanked
Attack of Opportunity;offensive;reaction;<b>Trigger</b> A creature within [name]'s reach uses a manipulate action or a move action, makes a ranged attack, or leaves a square during a move action it's using. <b>Effect</b> [Name] attempts a melee Strike against the triggering creature. If the attack is a critical hit and the trigger was a manipulate action, [name] disrupts that action. This Strike doesn't count toward [name]'s multiple attack penalty, and its multiple attack penalty doesn't apply to this Strike.
Buck;defensive;reaction;Most monsters that serve as mounts can attempt to buck off unwanted or annoying riders, but most mounts will not use this reaction against a trusted creature unless the mounts are spooked or mistreated. <b>Trigger</b> A creature Mounts or uses the Command an Animal action while riding the monster. <b>Effect</b> The triggering creature must succeed at a Reflex saving DC {DC} or fall off the creature and land prone. If the save is a critical failure, the triggering creature also takes 1d6 bludgeoning damage in addition to the normal damage for the fall.
Catch Rock;defensive;reaction;<b>Requirements</b> [Name] must have a free hand but can Release anything it's holding as part of this reaction. <b>Trigger</b> [Name] is targeted with a thrown rock Strike or a rock would fall on the monster. <b>Effect</b> [Name] gains a +4 circumstance bonus to its AC against the triggering attack or to any defense against the falling rock. If the attack misses or [name] successfully defends against the falling rock, [he/she/it] catches the rock, takes no damage, and is now holding the rock.
Constrict;offensive;1 action;Name deals the listed amount of damage to any number of creatures grabbed or restrained by it. Each of those creatures can attempt a basic Fortitude save with the listed DC.
Ferocity;defensive;reaction;<b>Trigger</b> [Name] is reduced to 0 HP. <b>Effect</b> [Name] avoids being knocked out and remains at 1 HP, but [his/her/its] wounded value increases by 1. When [he/she/it] is wounded 3, [he/she/it] can no longer use this ability.
Grab;offensive;1 action;<b>Requirements</b> [Name]'s last action was a successful Strike that lists Grab in its damage entry, or [name] has a creature grabbed or restrained <b>Effect</b> If used after a Strike, [name] attempts to Grapple the creature using the body part [he/she/it] attacked with. This attempt neither applies nor counts toward [name]'s multiple attack penalty. [Name] can instead use Grab and choose one creature [he/she/it]'s grabbing or restraining with an appendage that has Grab to automatically extend that condition to the end of [name]'s next turn.
Greater Constrict;offensive;1 action;[Name] deals the listed amount of damage to any number of creatures grabbed or restrained by [him/her/it]. Each of those creatures can attempt a basic Fortitude save with the listed DC. A creature that fails this save falls unconscious, and a creature that succeeds is then temporarily immune to falling unconscious from Greater Constrict for 1 minute.
Improved Grab;offensive;free action;[Name] can use Grab as a free action triggered by a hit with [his/her/its] initial attack. [Name] still needs to spend an action to extend the duration for creatures [he/she/it] already has grabbed.
Improved Knockdown;offensive;free action;[Name] can use Knockdown as a free action triggered by a hit with its initial attack.
Melee;offensive;1 action;{Weapon} {Attack Bonus}, <b>Damage</b> {Damage}.
Ranged;offensive;1 action;{Weapon} {Attack Bonus}, <b>Damage</b> {Damage}.
Affliction;offensive;;({Affliction Type:disease}) <b>Saving Throw</b> {Saving Throw}, <b>Stage 1</b> Text <b>Stage 2</b> Text <b>Stage 3</b> Text
Knockdown;offensive;1 action;<b>Requirements</b> The monster's last action was a success with a Strike that lists Knockdown in its damage entry. <b>Effect</b> The monster knocks the target prone.
Saving Throw;offensive;;{Description} <b>Critical Success</b> {Critical Success} <b>Success</b> {Success} <b>Failure</b> {Failure} <b>Critical Failure</b> {Critical Failure}. 
"""

# Waiting for Remaster
